/**
 * Dev-only marketplace rows for `prisma/seed.ts` when `ALLOW_DEMO_SEED=true`.
 * Not imported by Next.js app routes — the app reads listings from the database.
 */
import type { MarketplaceListing } from "../src/content/marketplace-listings";

export const seedMarketplaceListings: MarketplaceListing[] = [
  {
    id: "m1",
    title: "2019 NBA Hoops Zion Williamson RC PSA 10",
    price: 420,
    imageSeed: "mp-zion-hoops",
    sellerUsername: "CardVaultBreaks",
    sellerRating: 4.95,
    sellerVerified: true,
    category: "Trading Cards",
    buyingFormat: "buy_now",
    condition: "PSA 10",
    listedAt: "2026-04-28T15:20:00Z",
    vaultPick: true,
    href: "/marketplace/m1",
    allowOffers: true,
    minimumOfferUsd: 350,
  },
  {
    id: "m2",
    title: "Jordan 1986 Fleer #57 Rookie BGS 9.5",
    price: 12800,
    imageSeed: "mp-jordan-fleer",
    sellerUsername: "SlabCity",
    sellerRating: 4.88,
    sellerVerified: true,
    category: "Trading Cards",
    buyingFormat: "auction",
    auctionTimeLeft: "2h left",
    condition: "BGS 9.5",
    listedAt: "2026-04-27T11:00:00Z",
    vaultPick: true,
    href: "/marketplace/m2",
    allowOffers: false,
  },
  {
    id: "m3",
    title: "LeBron James Topps Chrome RC PSA 9",
    price: 2100,
    imageSeed: "mp-lebron-chrome",
    sellerUsername: "GrailGarage",
    sellerRating: 4.72,
    sellerVerified: true,
    category: "Trading Cards",
    buyingFormat: "buy_now",
    condition: "PSA 9",
    listedAt: "2026-04-26T09:30:00Z",
    href: "/marketplace/m3",
  },
  {
    id: "m4",
    title: "Tom Brady Signed Patriots Mini Helmet (UDA)",
    price: 1895,
    imageSeed: "mp-brady-helmet",
    sellerUsername: "InkAndLeather",
    sellerRating: 4.91,
    sellerVerified: true,
    category: "Memorabilia",
    buyingFormat: "auction",
    auctionTimeLeft: "1d 4h left",
    condition: "Authenticated",
    listedAt: "2026-04-25T18:45:00Z",
    vaultPick: true,
    href: "/marketplace/m4",
    allowOffers: true,
  },
  {
    id: "m5",
    title: "Kobe Bryant Game-Used Photo-Matched Jersey Piece",
    price: 6400,
    imageSeed: "mp-kobe-jersey",
    sellerUsername: "HallOfFrames",
    sellerRating: 4.65,
    sellerVerified: false,
    category: "Memorabilia",
    buyingFormat: "auction",
    auctionTimeLeft: "27m left",
    condition: "LOA",
    listedAt: "2026-04-24T20:10:00Z",
    href: "/marketplace/m5",
  },
  {
    id: "m6",
    title: "Rolex Submariner Date 41mm 2022 Full Set",
    price: 14250,
    imageSeed: "mp-rolex-sub",
    sellerUsername: "CrownTrade",
    sellerRating: 4.98,
    sellerVerified: true,
    category: "Watches",
    buyingFormat: "buy_now",
    condition: "Unworn",
    listedAt: "2026-04-29T08:00:00Z",
    href: "/marketplace/m6",
    allowOffers: true,
  },
  {
    id: "m7",
    title: "Omega Speedmaster Moonwatch Sapphire",
    price: 5650,
    imageSeed: "mp-omega-moon",
    sellerUsername: "TickVault",
    sellerRating: 4.81,
    sellerVerified: true,
    category: "Watches",
    buyingFormat: "auction",
    auctionTimeLeft: "45m left",
    condition: "Excellent",
    listedAt: "2026-04-22T12:00:00Z",
    href: "/marketplace/m7",
    allowOffers: true,
  },
  {
    id: "m8",
    title: "Air Jordan 1 Chicago 2015 — DS Size 11",
    price: 1680,
    imageSeed: "mp-aj1-chicago",
    sellerUsername: "SoleProof",
    sellerRating: 4.77,
    sellerVerified: true,
    category: "Sneakers",
    buyingFormat: "buy_now",
    condition: "DS",
    listedAt: "2026-04-29T10:15:00Z",
    href: "/marketplace/m8",
  },
  {
    id: "m9",
    title: "Nike Dunk Low Panda — DS Size 9",
    price: 185,
    imageSeed: "mp-dunk-panda",
    sellerUsername: "SoleProof",
    sellerRating: 4.77,
    sellerVerified: true,
    category: "Sneakers",
    buyingFormat: "buy_now",
    condition: "DS",
    listedAt: "2026-04-20T16:40:00Z",
    href: "/marketplace/m9",
  },
  {
    id: "m10",
    title: "Vintage Pokémon Base Set Charizard Holo PSA 7",
    price: 3200,
    imageSeed: "mp-charizard-base",
    sellerUsername: "RetroRipz",
    sellerRating: 4.58,
    sellerVerified: true,
    category: "Other",
    buyingFormat: "auction",
    auctionTimeLeft: "5h left",
    condition: "PSA 7",
    listedAt: "2026-04-23T14:22:00Z",
    href: "/marketplace/m10",
  },
  {
    id: "m11",
    title: "Patrick Mahomes Optic Rated Rookie PSA 10",
    price: 890,
    imageSeed: "mp-mahomes-optic",
    sellerUsername: "CardVaultBreaks",
    sellerRating: 4.95,
    sellerVerified: true,
    category: "Trading Cards",
    buyingFormat: "buy_now",
    condition: "PSA 10",
    listedAt: "2026-04-21T07:55:00Z",
    href: "/marketplace/m11",
  },
  {
    id: "m12",
    title: "Mickey Mantle 1956 Topps #135 VG-EX",
    price: 475,
    imageSeed: "mp-mantle-56",
    sellerUsername: "PaperClassics",
    sellerRating: 4.42,
    sellerVerified: false,
    category: "Trading Cards",
    buyingFormat: "auction",
    auctionTimeLeft: "18h left",
    condition: "Raw",
    listedAt: "2026-04-19T13:08:00Z",
    href: "/marketplace/m12",
  },
];
