/** Shared seller console terminology — keep aligned with mobile `sellerConsoleCopy.ts`. */
export const SELLER_CONSOLE = {
  screenTitle: 'Command center',
  lineup: 'Lineup',
  addItem: 'Add item',
  shareShow: 'Share show',
  goLive: 'Go live',
  startStream: 'Start stream',
  pauseStream: 'Pause',
  resumeStream: 'Resume',
  stopStream: 'Stop stream',
  endShow: 'End show',
  obsSetup: 'OBS / RTMP',
  camera: 'Camera',
  microphone: 'Microphone',
  previewHint: 'Check your camera and mic, then go live. You stay in the command center.',
  copyLink: 'Copy link',
  nativeShare: 'Share…',
  shareInApp: 'Share in Get Vaulted',
  sendToFollowing: 'Send to someone you follow',
  notifyMyFollowers: 'Notify my followers',
  shareOutside: 'Share outside the app',
  inviteFollowers: 'Invite followers',
  stats: 'Show stats',
  chat: 'Chat',
  viewers: 'Viewers',
  scheduled: 'Scheduled',
  /** Add-item modal — top-level sale categories */
  saleCategoryTeamsDivisions: 'Teams/Divisions',
  saleCategoryAuction: 'Auction',
  saleCategoryBuyNow: 'Buy Now',
  /** Add-item modal — inventory source tabs */
  addSourceNew: 'New item',
  addSourceShop: 'From my shop',
  addSourceCopyShow: 'Copy last show',
  addSourceShopHint: 'Pull Live show or Marketplace inventory into this lineup.',
  addSourceCopyHint: 'Clone unsold lots from a previous show.',
} as const;
