import { StyleSheet } from 'react-native';
import { colors, radii, spacing } from '../../theme';

/** Premium dark Vault Wallet visual system — Get Vaulted branded, not Whatnot. */
export const vaultWalletTheme = StyleSheet.create({
  backdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.72)',
  },
  sheet: {
    backgroundColor: '#0c0b10',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderColor: 'rgba(201,162,39,0.28)',
    flexShrink: 1,
    shadowColor: '#c9a227',
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -4 },
    elevation: 12,
  },
  handle: {
    alignSelf: 'center',
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.18)',
    marginBottom: spacing.md,
  },
  hero: {
    alignItems: 'center',
    paddingVertical: spacing.sm,
    marginBottom: spacing.md,
    gap: 6,
  },
  heroIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(201,162,39,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(201,162,39,0.35)',
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#faf8f2',
    letterSpacing: -0.4,
  },
  heroSub: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.52)',
    textAlign: 'center',
    lineHeight: 17,
    paddingHorizontal: spacing.md,
  },
  readinessPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: radii.pill,
    borderWidth: 1,
  },
  readinessReady: {
    borderColor: 'rgba(52,211,153,0.35)',
    backgroundColor: 'rgba(16,185,129,0.1)',
  },
  readinessSetup: {
    borderColor: 'rgba(201,162,39,0.35)',
    backgroundColor: 'rgba(201,162,39,0.08)',
  },
  readinessTxt: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  readinessTxtReady: { color: '#6ee7b7' },
  readinessTxtSetup: { color: colors.gold },
  sectionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    minHeight: 72,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(255,255,255,0.035)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.09)',
    marginBottom: spacing.sm,
  },
  sectionCardPressed: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(201,162,39,0.22)',
  },
  sectionIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(201,162,39,0.1)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(201,162,39,0.25)',
  },
  sectionBody: { flex: 1, minWidth: 0, gap: 3 },
  sectionTitle: { color: '#f4f2ec', fontSize: 15, fontWeight: '800' },
  sectionSub: { color: 'rgba(255,255,255,0.55)', fontSize: 12, lineHeight: 16 },
  sectionSubWarn: { color: '#fbbf24', fontSize: 12, fontWeight: '700' },
  sectionAmount: { color: colors.gold, fontSize: 13, fontWeight: '800' },
  chevron: { opacity: 0.45 },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
    minHeight: 36,
  },
  headerSpacer: { width: 32 },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '900',
    color: '#faf8f2',
  },
  scrollContent: { paddingBottom: spacing.md, gap: spacing.sm },
  footer: {
    paddingTop: spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.08)',
    gap: spacing.sm,
  },
  primaryBtn: {
    minHeight: 52,
    borderRadius: radii.lg,
    backgroundColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  primaryBtnDisabled: { opacity: 0.45 },
  primaryBtnText: { color: '#0a0908', fontSize: 15, fontWeight: '900' },
  secondaryBtn: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryBtnText: { color: colors.gold, fontSize: 14, fontWeight: '800' },
  detailCard: {
    borderRadius: radii.lg,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.1)',
    padding: spacing.md,
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  detailTitle: { color: '#fff', fontSize: 14, fontWeight: '800' },
  detailBody: { color: 'rgba(255,255,255,0.62)', fontSize: 12, lineHeight: 17 },
  badge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(201,162,39,0.12)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(201,162,39,0.3)',
  },
  badgeText: { color: colors.gold, fontSize: 10, fontWeight: '800' },
  linkBtn: { alignSelf: 'flex-start', paddingVertical: 6 },
  linkBtnText: { color: colors.gold, fontSize: 13, fontWeight: '800' },
  errorText: { color: '#fca5a5', fontSize: 12, fontWeight: '600', marginBottom: spacing.sm },
  hintText: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 11,
    lineHeight: 16,
    marginBottom: spacing.sm,
  },
  pmRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  pmIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  pmActions: { flexDirection: 'row', gap: spacing.sm },
  pmActionTxt: { color: colors.gold, fontSize: 11, fontWeight: '800' },
  promoInput: {
    borderRadius: radii.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(0,0,0,0.35)',
    color: '#fff',
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    fontSize: 14,
    marginBottom: spacing.sm,
  },
  payOptionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
  payOptionBtnText: {
    flex: 1,
    color: '#f4f2ec',
    fontSize: 14,
    fontWeight: '800',
  },
  fieldLabel: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  formInput: {
    borderRadius: radii.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(0,0,0,0.35)',
    color: '#fff',
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    fontSize: 14,
    marginBottom: spacing.sm,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginTop: spacing.xs,
  },
  switchLabel: {
    flex: 1,
    color: '#f4f2ec',
    fontSize: 13,
    fontWeight: '700',
  },
});
