import { StyleSheet } from 'react-native';
import { colors, radii, spacing } from '../../theme';
import { WALLET_CARD_FORM_HEIGHT } from './walletCardFieldStyle';

export const walletPaymentSetupStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
  },
  panelShell: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  panel: {
    flex: 1,
    marginTop: spacing.md,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: '#F7F7F8',
    overflow: 'hidden',
  },
  body: {
    flex: 1,
  },
  keyboardFrame: {
    flex: 1,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    minHeight: 52,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E4E4E7',
    backgroundColor: '#FFFFFF',
  },
  headerSpacer: { width: 32 },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '800',
    color: '#18181B',
    letterSpacing: -0.3,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.lg,
    gap: spacing.lg,
  },
  subtitle: {
    color: '#52525B',
    fontSize: 15,
    lineHeight: 22,
  },
  section: {
    gap: spacing.sm,
  },
  sectionTitle: {
    color: '#18181B',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#E4E4E7',
    padding: spacing.md,
    gap: spacing.md,
  },
  methodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  methodIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F4F4F5',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E4E4E7',
  },
  methodTextBlock: {
    flex: 1,
    gap: 2,
  },
  methodTitle: {
    color: '#18181B',
    fontSize: 16,
    fontWeight: '700',
  },
  methodSub: {
    color: '#71717A',
    fontSize: 13,
    lineHeight: 18,
  },
  scanHint: {
    color: '#71717A',
    fontSize: 13,
    lineHeight: 18,
  },
  cardFormWrap: {
    backgroundColor: '#FFFFFF',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#D4D4D8',
    overflow: 'hidden',
  },
  cardForm: {
    width: '100%',
    height: WALLET_CARD_FORM_HEIGHT,
    marginVertical: 0,
  },
  fieldLabel: {
    color: '#3F3F46',
    fontSize: 14,
    fontWeight: '700',
  },
  fieldRow: {
    minHeight: 52,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#D4D4D8',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldValue: {
    color: '#18181B',
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    opacity: 0.55,
  },
  switchLabel: {
    color: '#52525B',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  switchHint: {
    color: '#A1A1AA',
    fontSize: 12,
  },
  footer: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#E4E4E7',
    backgroundColor: '#FFFFFF',
  },
  primaryBtn: {
    minHeight: 54,
    borderRadius: radii.md,
    backgroundColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  primaryBtnDisabled: { opacity: 0.45 },
  primaryBtnText: {
    color: '#0A0A0A',
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  secondaryBtn: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.sm,
  },
  secondaryBtnText: {
    color: '#52525B',
    fontSize: 14,
    fontWeight: '700',
  },
  errorText: { color: '#DC2626', fontSize: 14, fontWeight: '600', lineHeight: 20 },
  hintText: {
    color: '#71717A',
    fontSize: 13,
    lineHeight: 18,
  },
  loadingBlock: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
  },
  loadingText: { color: '#71717A', fontSize: 15, textAlign: 'center' },
  countryPickerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  countryPickerSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '55%',
    paddingBottom: spacing.lg,
  },
  countryPickerTitle: {
    color: '#18181B',
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
    paddingVertical: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E4E4E7',
  },
  countryOption: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#F4F4F5',
  },
  countryOptionSelected: {
    backgroundColor: '#FFFBEB',
  },
  countryOptionText: {
    color: '#18181B',
    fontSize: 16,
    fontWeight: '600',
  },
});
