import { Platform, StyleSheet } from 'react-native';
import { colors, radii, spacing } from '../../theme';
import { WALLET_CARD_FORM_HEIGHT } from './walletCardFieldStyle';

const VAULT_BG = '#0c0b10';
const VAULT_SURFACE = 'rgba(255,255,255,0.045)';
const VAULT_BORDER = 'rgba(255,255,255,0.09)';

export const walletPaymentSetupStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
  },
  panelShell: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  embeddedShell: {
    flex: 1,
    width: '100%',
  },
  embeddedPanel: {
    flex: 1,
    backgroundColor: VAULT_BG,
  },
  panelDark: {
    flex: 1,
    marginTop: spacing.md,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: VAULT_BG,
    overflow: 'hidden',
    borderTopWidth: 1,
    borderColor: 'rgba(201,162,39,0.28)',
  },
  body: {
    flex: 1,
    backgroundColor: VAULT_BG,
  },
  keyboardFrame: {
    flex: 1,
  },
  headerBlock: {
    paddingBottom: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  headerRowDark: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    minHeight: 48,
  },
  headerSpacer: { width: 36 },
  headerBackBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: VAULT_BORDER,
  },
  headerTitleDark: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '900',
    color: '#faf8f2',
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    color: 'rgba(255,255,255,0.52)',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    paddingHorizontal: spacing.xl,
    marginTop: spacing.xs,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl,
    gap: spacing.lg,
  },
  pickerScrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xxxl,
    gap: spacing.sm,
  },
  sectionLabel: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: spacing.xs,
  },
  methodCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    borderRadius: 16,
    backgroundColor: VAULT_SURFACE,
    borderWidth: 1,
    borderColor: VAULT_BORDER,
  },
  methodCardPressed: {
    backgroundColor: 'rgba(201,162,39,0.08)',
    borderColor: 'rgba(201,162,39,0.28)',
  },
  methodIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(201,162,39,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(201,162,39,0.22)',
  },
  methodTextBlock: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  methodTitle: {
    color: '#f4f2ec',
    fontSize: 16,
    fontWeight: '800',
  },
  methodSub: {
    color: 'rgba(255,255,255,0.48)',
    fontSize: 13,
    lineHeight: 18,
  },
  methodBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(52,211,153,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(52,211,153,0.35)',
  },
  methodBadgeText: {
    color: '#6ee7b7',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  cardEntrySection: {
    gap: spacing.sm,
  },
  stripeCardShell: {
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    padding: spacing.sm,
  },
  stripeCardInner: {
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.14,
        shadowRadius: 16,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  cardForm: {
    width: '100%',
    height: WALLET_CARD_FORM_HEIGHT,
    marginVertical: 0,
  },
  cardFormLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: WALLET_CARD_FORM_HEIGHT,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
  },
  trustBlock: {
    gap: spacing.xs,
    padding: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: VAULT_SURFACE,
    borderWidth: 1,
    borderColor: VAULT_BORDER,
  },
  trustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  trustTitle: {
    color: '#f4f2ec',
    fontSize: 14,
    fontWeight: '800',
  },
  trustBody: {
    color: 'rgba(255,255,255,0.48)',
    fontSize: 13,
    lineHeight: 19,
    paddingLeft: 26,
  },
  footer: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.08)',
    backgroundColor: VAULT_BG,
  },
  primaryBtn: {
    minHeight: 54,
    borderRadius: radii.md,
    backgroundColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  primaryBtnDisabled: {
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  primaryBtnSuccess: {
    backgroundColor: 'rgba(52,211,153,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(52,211,153,0.35)',
  },
  primaryBtnText: {
    color: '#111111',
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  primaryBtnTextDisabled: {
    color: 'rgba(255,255,255,0.32)',
  },
  primaryBtnTextSuccess: {
    color: '#6ee7b7',
  },
  errorText: {
    color: '#fca5a5',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    marginTop: spacing.xs,
  },
  successBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: 'rgba(52,211,153,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(52,211,153,0.3)',
  },
  successBannerText: {
    color: '#6ee7b7',
    fontSize: 14,
    fontWeight: '800',
    flex: 1,
  },
  loadingBlock: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
    backgroundColor: VAULT_BG,
  },
  loadingText: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
  },
  errorStateBlock: {
    flex: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xl,
    gap: spacing.md,
  },
  errorStateTitle: {
    color: '#faf8f2',
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
});
