import { StyleSheet } from 'react-native';
import { colors, radii, spacing } from '../../theme';
import { WALLET_CARD_FORM_HEIGHT } from './walletCardFieldStyle';

export const walletPaymentSetupStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
  },
  panelShell: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  panel: {
    flex: 1,
    marginTop: spacing.md,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: '#F7F7F8',
    overflow: 'hidden',
  },
  body: {
    flex: 1,
  },
  keyboardFrame: {
    flex: 1,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    minHeight: 52,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E4E4E7',
    backgroundColor: '#FFFFFF',
  },
  headerSpacer: { width: 32 },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '800',
    color: '#18181B',
    letterSpacing: -0.3,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.lg,
    gap: spacing.lg,
  },
  subtitle: {
    color: '#52525B',
    fontSize: 15,
    lineHeight: 22,
  },
  section: {
    gap: spacing.sm,
  },
  sectionTitle: {
    color: '#18181B',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#E4E4E7',
    padding: spacing.md,
    gap: spacing.md,
  },
  methodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  methodIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F4F4F5',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E4E4E7',
  },
  methodTextBlock: {
    flex: 1,
    gap: 2,
  },
  methodTitle: {
    color: '#18181B',
    fontSize: 16,
    fontWeight: '700',
  },
  methodSub: {
    color: '#71717A',
    fontSize: 13,
    lineHeight: 18,
  },
  scanHint: {
    color: '#71717A',
    fontSize: 13,
    lineHeight: 18,
  },
  cardFormWrap: {
    backgroundColor: '#FFFFFF',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    overflow: 'hidden',
  },
  cardForm: {
    width: '100%',
    height: WALLET_CARD_FORM_HEIGHT,
    marginVertical: 0,
  },
  cardFormLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  fieldLabel: {
    color: '#3F3F46',
    fontSize: 14,
    fontWeight: '700',
  },
  fieldRow: {
    minHeight: 52,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldValue: {
    color: '#111111',
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    opacity: 0.55,
  },
  switchLabel: {
    color: '#52525B',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  switchHint: {
    color: '#A1A1AA',
    fontSize: 12,
  },
  footer: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#E4E4E7',
    backgroundColor: '#FFFFFF',
  },
  primaryBtn: {
    minHeight: 54,
    borderRadius: radii.md,
    backgroundColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  primaryBtnDisabled: {
    backgroundColor: '#D4D4D8',
  },
  primaryBtnText: {
    color: '#111111',
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  primaryBtnTextDisabled: {
    color: '#374151',
  },
  secondaryBtn: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.sm,
  },
  secondaryBtnText: {
    color: '#52525B',
    fontSize: 14,
    fontWeight: '700',
  },
  errorText: { color: '#DC2626', fontSize: 14, fontWeight: '600', lineHeight: 20 },
  hintText: {
    color: '#71717A',
    fontSize: 13,
    lineHeight: 18,
  },
  loadingBlock: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
  },
  loadingText: { color: '#71717A', fontSize: 15, textAlign: 'center' },
  countryPickerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  countryPickerSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '55%',
    paddingBottom: spacing.lg,
  },
  countryPickerTitle: {
    color: '#18181B',
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
    paddingVertical: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E4E4E7',
  },
  countryOption: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#F4F4F5',
  },
  countryOptionSelected: {
    backgroundColor: '#FFFBEB',
  },
  countryOptionText: {
    color: '#18181B',
    fontSize: 16,
    fontWeight: '600',
  },
  panelDark: {
    flex: 1,
    marginTop: spacing.md,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: '#0c0b10',
    overflow: 'hidden',
    borderTopWidth: 1,
    borderColor: 'rgba(201,162,39,0.28)',
  },
  headerRowDark: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    minHeight: 52,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  headerTitleDark: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '900',
    color: '#faf8f2',
  },
  pickerSubtitle: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.md,
  },
  pickerList: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.lg,
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  pickerRowLast: {
    borderBottomWidth: 0,
  },
  pickerIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerRowTitle: {
    flex: 1,
    color: '#f4f2ec',
    fontSize: 16,
    fontWeight: '700',
  },
});
