/** Shared seller console terminology — keep aligned with web `seller-console-copy.ts`. */
export const SELLER_CONSOLE = {
  screenTitle: 'Command center',
  lineup: 'Lineup',
  addItem: 'Add item',
  shareShow: 'Share show',
  goLive: 'Go live',
  startStream: 'Start stream',
  pauseStream: 'Pause',
  resumeStream: 'Play',
  stopStream: 'Stop stream',
  endShow: 'End show',
  clutchTime: 'Clutch Time',
  clutchTimeHint: 'Sudden death — timer does not extend on bids.',
  obsSetup: 'OBS / RTMP',
  camera: 'Camera',
  microphone: 'Microphone',
  previewHint:
    'Phone camera Go Live, or use OBS / RTMP for desktop. After Connect OBS, Start show opens the room — video comes from OBS, not this phone.',
  resumeStreamHint: 'Show minimized — tap Play to bring the live feed back.',
  liveLeaveAppHint:
    'Leaving the app pauses your show for buyers. Tap Play when you return. Need the camera to stay on? Use OBS / RTMP.',
  obsBroadcastHint:
    'This show is set to OBS. Start show opens the room; keep Start Streaming on in OBS (WHIP). Tap Use this camera only if you want to switch off OBS to the phone.',
  obsLiveBadge: 'OBS live',
  obsWaitingSignal: 'Waiting for OBS — Start Streaming in OBS (WHIP), then Refresh status.',
  copyLink: 'Copy link',
  nativeShare: 'Share…',
  shareInApp: 'Share in Get Vaulted',
  sendToFollowing: 'Send to someone you follow',
  notifyMyFollowers: 'Notify my followers',
  shareOutside: 'Share outside the app',
  inviteFollowers: 'Invite followers',
  stats: 'Show stats',
  sales: 'Sales',
  chat: 'Chat',
  viewers: 'Viewers',
  scheduled: 'Scheduled',
  /** Add-item modal — top-level sale categories */
  saleCategoryTeamsDivisions: 'Teams/Divisions',
  saleCategoryAuction: 'Auction',
  saleCategoryBuyNow: 'Buy Now',
  /** Add-item modal — inventory source tabs */
  addSourceNew: 'New item',
  addSourceShop: 'From my shop',
  addSourceCopyShow: 'Copy last show',
  addSourceShopHint: 'Pull Live show or Marketplace inventory into this lineup.',
  addSourceCopyHint: 'Bring unsold lots from a previous show — finish a break you did not complete.',
  /** Companion host — another device owns the camera. */
  companionBannerTitle: 'Live on another device',
  companionBannerBody:
    'Camera is publishing from your other device. Use this phone for queue, pricing, and start auction — buyers keep that stream.',
  companionLiveBadge: 'Live elsewhere',
  companionTakeOverCamera: 'Use this camera',
} as const;
