/** Shared seller console terminology — keep aligned with web `seller-console-copy.ts`. */
export const SELLER_CONSOLE = {
  screenTitle: 'Command center',
  lineup: 'Lineup',
  addItem: 'Add item',
  shareShow: 'Share show',
  goLive: 'Go live',
  startStream: 'Start stream',
  pauseStream: 'Pause',
  resumeStream: 'Resume',
  stopStream: 'Stop stream',
  endShow: 'End show',
  clutchTime: 'Clutch Time',
  clutchTimeHint: 'Sudden death — timer resets on every bid.',
  obsSetup: 'OBS / RTMP',
  camera: 'Camera',
  microphone: 'Microphone',
  previewHint: 'Check your camera and mic, then go live. You stay in the command center.',
  copyLink: 'Copy link',
  nativeShare: 'Share…',
  inviteFollowers: 'Invite followers',
  stats: 'Show stats',
  sales: 'Sales',
  chat: 'Chat',
  viewers: 'Viewers',
  scheduled: 'Scheduled',
} as const;
