// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Match Next.js: `.env.local` overrides `.env` so CLI (`migrate`, `studio`) uses the same
// Postgres URL as `npm run dev` (see https://nextjs.org/docs/app/building-your-application/configuring/environment-variables).
config({ path: ".env" });
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
