// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Match Next.js: `.env.local` overrides `.env` so CLI (`migrate`, `studio`) uses the same
// Postgres URL as `npm run dev` (see https://nextjs.org/docs/app/building-your-application/configuring/environment-variables).
config({ path: ".env" });
config({ path: ".env.local" });

// Lets `prisma generate` (including `postinstall`) run before DATABASE_URL exists locally or in CI.
// Set DATABASE_URL in `.env` / `.env.local` (or the environment) for real migrations and runtime.
const databaseUrl =
  process.env.DATABASE_URL?.trim() ||
  "postgresql://127.0.0.1:5432/postgres?schema=public";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
